
DROP TABLE IF EXISTS USER;
CREATE TABLE USER(SEQ BIGINT auto_increment PRIMARY KEY, ID VARCHAR2(255), NAME  VARCHAR2(255), PASSWD  VARCHAR2(2000), REGTIME TIMESTAMP);
DROP TABLE IF EXISTS DIARY;
CREATE TABLE DIARY(SEQ BIGINT auto_increment  PRIMARY KEY, SUBJECT VARCHAR2(255), CONTENT  CLOB, REGTIME  TIMESTAMP, MODITIME TIMESTAMP);

alter table USER add column moditime timestamp;
alter table USER add column role ENUM('USER', 'ADMIN');
