
DROP TABLE IF EXISTS USER;
CREATE TABLE USER(SEQ BIGINT AUTO_INCREMENT PRIMARY KEY, ID VARCHAR2(255), NAME  VARCHAR2(255), PASSWD  VARCHAR2(2000), REGTIME TIMESTAMP);
DROP TABLE IF EXISTS DIARY;
CREATE TABLE DIARY(SEQ BIGINT AUTO_INCREMENT  PRIMARY KEY, SUBJECT VARCHAR2(255), CONTENT  CLOB, REGTIME  TIMESTAMP, MODITIME TIMESTAMP);

ALTER TABLE USER ADD COLUMN MODITIME TIMESTAMP;
ALTER TABLE USER ADD COLUMN ROLE ENUM('USER', 'ADMIN');
ALTER TABLE USER ADD COLUMN FIRST_NAME VARCHAR2(255);
ALTER TABLE USER ALTER COLUMN NAME RENAME TO LAST_NAME;
